### ISSUE TITLE
typo: Line 21 of HotVoice.AHK v0.1.3 references 'nanme'

### ISSUE THREAD

**Issue by hughfuve** [evilC/HotVoice#3]
Line 21 of HotVoice.AHK v0.1.3 references 'nanme', 
`
LoadGrammar(grammar, name, callback){
		if (this._grammarCallbacks.HasKey(nanme)){
	
`

**Comment by evilC** [comment]
Could you raise a new issue with the reproduction steps for the culture issue?  
Have fixed the typo issue, will make a release soon.
